# Generated by Django 5.0.6 on 2024-12-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=50)),
                ('tcg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('psa_9_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('psa_10_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
