# Generated by Django 5.0.6 on 2024-12-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='card_name',
        ),
    ]
