# Generated by Django 5.0.6 on 2024-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_name_card_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='psa_10_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='psa_9_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
