# Generated by Django 5.0.6 on 2024-12-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_card_psa_10_price_alter_card_psa_9_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='cards',
        ),
    ]
